### ISSUE TITLE
Agent stalled mid-reply

### ISSUE THREAD

**Issue by dekdynamics** [OpenAgentsInc/openagents#419]
Hi Team,

I get this behaviour very often:

![image](https://github.com/OpenAgentsInc/openagents/assets/81862609/3fc6ecc0-736d-4224-af55-baaba38194f6)

While this is happening, I can't stop the reply or say anything new in the chat.

This one has been stuck for ~10 minutes, but typically it never returns and I start a new chat.

**Comment by svemir** [comment]
We are limited by how livewire streaming works here. See https://github.com/livewire/livewire/discussions/7882

Perhaps in this specific case there is a simpler answer, but we would have to replicate the issue locally first.

**Comment by dekdynamics** [comment]
Try the same question for the Fast Talking Man agent. It happens to me every time I ask this question.

I just tried again right now and its been stuck here for over 2 minutes:

![image](https://github.com/OpenAgentsInc/openagents/assets/81862609/acb037e1-da25-4737-a3ed-a607a9f256c2)
