### ISSUE TITLE
No response from agent

### ISSUE THREAD

**Issue by dekdynamics** [OpenAgentsInc/openagents#426]
Hi - This is a followup to my previous issue that was closed as fixed.

I removed all of the documents from the agent repo except for the lightning whitepaper, and I asked a more direct question:

![image](https://github.com/OpenAgentsInc/openagents/assets/81862609/36d69486-6f23-47a7-9478-61bc7eea45d4)

Its been a few minutes like this. 

The first page of the pdf has the answer:

<img width="543" alt="image" src="https://github.com/OpenAgentsInc/openagents/assets/81862609/c8c168db-85a0-4e59-8e75-077b6a395a87">

**Comment by AtlantisPleb** [comment]
Looks fixed, please reopen if you encounter it again
