### ISSUE TITLE
Issue: Agent replies are missing words

### ISSUE THREAD

**Issue by dekdynamics** [OpenAgentsInc/openagents#431]
After the latest update, the agent replies quickly, however this question never gets a proper answer:

![image](https://github.com/OpenAgentsInc/openagents/assets/81862609/2d477a14-a5de-431a-b4e8-41958d145c7b)

Note that the 2nd and 5th messages are also from the agent, even though it says "You."

I considered for a moment that Poon, as in Joseph Poon, might be a banned word. There is definitely something interesting about the word:

![image](https://github.com/OpenAgentsInc/openagents/assets/81862609/7f0ddd7a-5903-4b90-84e8-ca31d7d52ec5)

Other answers are much better and faster than before.

**Comment by svemir** [comment]
This is not an issue on OpenAgents end. OA currently uses the comman-r-plus model to pose the final question (after combining the user prompt, the agent instructions, and the rag context.) Here is what I get when I ask this question from command-r-plus directly on Cohere website:

<img width="736" alt="Screenshot 2024-05-28 at 9 08 09 PM" src="https://github.com/OpenAgentsInc/openagents/assets/154453/bece5047-3ee2-401b-9c69-f6a1f024e9ab">

**Comment by AtlantisPleb** [comment]
Hilarious. We'll accelerate allowing agent builders to specify different base models.
